### ISSUE TITLE
ESP32 not supported?

### ISSUE THREAD

**Issue by nohkumado** [muwerk/muwerk#2]
Hello!
trying to get MQTT working on a ESP32 Devkit1, loaded your libraries into the arduino IDE, but hit immediately a problem:

Arduino: 1.8.12 (Linux), Board: "ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, None"

In file included from /home/bboett/Arduino/libraries/Muwerk_scheduler_library/scheduler.h:37:0,
                 from /home/bboett/Arduino/Tankwaechter/Tankwaechter.ino:15:
/home/bboett/Arduino/libraries/Muwerk_ustd_library/platform.h:118:2: error: #error Unkown platform. Please use one of the platform defines __ATTINY__, __ATMEGA__, __ESP__, __linux__, __APPLE__
 #error Unkown platform. Please use one of the platform defines __ATTINY__, __ATMEGA__, __ESP__, __linux__, __APPLE__
  ^
In file included from /home/bboett/Arduino/Tankwaechter/Tankwaechter.ino:17:0:
/home/bboett/Arduino/libraries/munet/mqtt.h:9:26: fatal error: Arduino_JSON.h: No such file or directory
compilation terminated.
exit status 1
Fehler beim Kompilieren für das Board ESP32 Dev Module.

so it seems that i am missing some libraries? which ones?

and BTW i didn't find any pio binary.... and a search gives me way too much hits:
 apt-cache search pio|wc -l
82
so that one will be hard to find.... but your alternate method from the arduino ide seemed to work, at least it reported a successful upload of the json file.....

thanks in advance for setting me up!

**Comment by domschl** [comment]
Before including anything from muwerk project, you need to make [platform defines](https://github.com/muwerk/ustd#platform-defines) to let the libraries know, which hardware you are using. In case of ESP32, simply add:
```cpp
#define    __ESP__        1
#define    __ESP32__      1
```
_before_ the #includes.

**Comment by nohkumado** [comment]
hmmm previous comment didn't make it....
ok! that brings me further, would be nice to add those values to the sample code in https://github.com/muwerk/munet line 1
thanks, next problem posted in issues of ustd.... sorry...
