### ISSUE TITLE
Format helpers for publish method

### ISSUE THREAD

**Issue by tuxpoldo** [muwerk/muwerk#4]
A typical and very frequently used programming pattern is:
```cpp
            char buf[32];
            sprintf(buf, "%5.1f", humidityVal);
            pSched->publish(name + "/sensor/humidity", buf);
```

The redundancy can be reduced by supplying a new method `publishf` that would support parameter formatting. This would allow to write:
```cpp
            pSched->publishf(name + "/sensor/humidity", "%5.1f", humidityVal);
```

**Comment by domschl** [comment]
We could add that to muwerk, this however requires to make sure that it works with the Arduino-Family.
Alternatively, it could be added mup_util.h in muwerk/mupplets?

**Comment by domschl** [comment]
I suggest putting it into mup_util.h, since:
* it uses a lot of heap storage (more than entire muwerk!)
* introduces a static MAX_MESSAGE_SIZE
